refactor: structured logging in applogic
phnx-im/infra pull request #266
Opened 2024-12-18 11:07 UTC by boxdot

Use tracing for logging in applogic. Replace the simplelog implementation with tracing-subscriber. Implement a tracing layer for sending logs to the Dart side. The layer is used in Android and iOS. On desktop, the logs are printed to the console via the tracing-subscriber formatter.

Also configure the logging formatting in Dart to use the same format as the Rust tracing logging. Logs from Dart are prefixed with `[F]` and logs from Rust are prefixed with `[R]`.

2024-12-19 12:11 UTC, raphaelrobert requested changes
Thanks, just a nit. We should also look into logging during the background execution induced by push notifications in a follow-up.

2024-12-19 12:11 UTC, raphaelrobert commented on applogic/src/logging/mod.rs
> +// SPDX-FileCopyrightText: 2023 Phoenix R&D GmbH <hello@phnx.im>
```suggestion
// SPDX-FileCopyrightText: 2024 Phoenix R&D GmbH <hello@phnx.im>
```

2024-12-20 09:06 UTC, boxdot commented on applogic/src/logging/mod.rs
> +// SPDX-FileCopyrightText: 2023 Phoenix R&D GmbH <hello@phnx.im>
Thanks!

2024-12-20 09:59 UTC, raphaelrobert approved these changes

2024-12-20 10:11 UTC, merged