ci: Flutter test
phnx-im/infra pull request #276
Opened 2024-12-23 08:46 UTC by raphaelrobert

This PR runs `flutter analyze` and `flutter test` on the CI.
Fixes #245.

2025-01-02 15:46 UTC, boxdot requested changes

2025-01-02 15:46 UTC, boxdot commented on justfile
> +    flutter analyze
Most likely, this needs to be prefixed with `fvm`, right?

2025-01-02 16:35 UTC, raphaelrobert commented on justfile
> +    flutter analyze
This is a bit of an open question, I should have brought that up earlier. Right now, the CI installs the Flutter version specified in the `.fvmrc` file. However, it doesn't install `fvm` as such, and therefore we don't need to prefix the command with `fvm` for it to work.
While that's fine for the CI, we as developers need to make a choice: Either we make sure we have the right flutter version installed, or we use `fvm`. If we use `fvm`, we should use an alias, otherwise we can't use the `justfile`. The recommendation is to have an alias like `flutter = flutter fvm`.

The alternative to the above would be to install & use `fvm` on the CI. The downside is that every developer has to use `fvm` in that case.

2025-01-03 11:09 UTC, boxdot commented on justfile
> +    flutter analyze
Thank you for the explanation. Let's keep it as is then.

2025-01-03 11:09 UTC, boxdot approved these changes

2025-01-03 15:25 UTC, merged